# Use the DATABASE_URL environment variable to specify the full connection URL for your database
default: &default
  url: <%= ENV["DATABASE_URL"] %>

# Set the pool size to 10
  pool: 10

# Set the encoding to UTF-8
  encoding: unicode

development:
  <<: *default

# Use the DATABASE_URL environment variable to specify the full connection URL for your database
test:
  <<: *default

# Use the DATABASE_URL environment variable to specify the full connection URL for your database
production:
  <<: *default
